### ISSUE TITLE
Transit / Solrad / Poppy Program

### ISSUE THREAD

**Issue by Gupyzer0** [Gupyzer0/Bluedog_Design_Bureau_Contracts#26]
# Specific missions
| Spacecraft | Launcher |
| --- | --- |
| Transit 1A | Thor-Able |
| Transit 1B + Solrad/GRAB mockup| Thor-Ablestar |
| Transit 2A + Solrad/GRAB | Thor-Ablestar |
| Transit 3A + Solrad/GRAB | Thor-Ablestar |
| Transit 3B + LOFTI | Thor Ablestar |
| Transit 4A + Injun 1 + Solrad 3/Grab 2 | Thor-Ablestar |
| Transit 5C | Scout-X4 |

### TODO
- [x] Transit 1A
- [x] Transit 1B + Solrad/GRAB mockup
- [x] Transit 2A + Solrad/GRAB
- [x] Transit 3A + Solrad/GRAB
- [x] Transit 3B + LOFTI
- [x] Transit 4A + Injun 1 + Solrad 3/Grab 2
- [x] Transit 5C

# Grouped missions - _make generator_
| BDB Spacecraft | Launcher | N° |
| --- | --- | --- |
| Poppy Block 1 (2/3 satellites) | Thor-Agena D | 8 |
| Poppy Block 2 (4 satellites) | Thorad-SLV2G Agena-D | 2 |
| Transit 5A | Scout-X3 | 3 |
| Transit 5E + Transit 5BN | Thor-Ablestar | 3 | 
| Transit-O | Scout-A | 22 |
| Transit-O SOOS | Scout-G1| 10 |

### TODO
- [x] Transit 5A
- [x] Transit 5E + Transit 5BN
- [x] Poppy Block 1,2
- [x] Transit-O | Scout-A
- [x] Transit-O SOOS

### Extra TODO
- [x] Explorer 30 requirements _Solrad 8 is Explorer 30 payload._
